runtime: python
env: flex

automatic_scaling:
  min_num_instances: 1  # Minimum number of instances to keep running
  max_num_instances: 1  # Maximum number of instances that can be created

handlers:
  - url: /.*
    script: auto
