runtime: python
env: flex

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 1
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.65
